name = "Fleefermon 3"
author = "Fleefie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3009f36b2c224de857775e02bf880a5f4d82fd27d8315658735e8fcb42dbd3d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
