name = "Fleefermon 3"
author = "Fleefie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92e3f2ad363ad5a8881c77c591dc159419f060d924201ed928e1c1c14131c453"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
