name = "Fleefermon 3"
author = "Fleefie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64e5a33ed8ff17ea76aead23556cc85715d607807bce47753a032d21409aa89d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"

[options]
datapack-folder = "config/openloader/data"
