name = "Fleefermon 3"
author = "Fleefie"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78944225e83f119ea92a495b20963bfe9d106d2e3f2edc87db796bad05859e26"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"

[options]
datapack-folder = "config/openloader/data"
